name: LaTeX PDF Build

on:
  push:
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up LaTeX
        run: sudo apt-get install texlive-full

      - name: Compile LaTeX document
        run: pdflatex -interaction=nonstopmode -output-directory=docs docs/main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: docs/main.pdf